#!/usr/bin/env bash
#* do not edit this file - it should only be built with the 'build-qpkgs.sh' script
#
# clamav.sh
#	Copyright (C) 2020-2023 OneCD - one.cd.only@gmail.com
#
# 	so, blame OneCD if it all goes horribly wrong. ;)
#
# Description:
#	This is a type 4 service-script: https://github.com/OneCDOnly/sherpa/wiki/Service-Script-Types
#
# Project:
#	https://git.io/sherpa
#
# Forum:
#	https://forum.qnap.com/viewtopic.php?f=320&t=132373

readonly USER_ARGS_RAW=$*
readonly QPKG_NAME=ClamAV
readonly SERVICE_SCRIPT_VERSION="230821"

Init()
	{

	# modify library defaults

	allow_access_to_sys_packages=true
	backup_pathfile=undefined
	install_pip_deps=true
	pip_cache_path=undefined
	qpkg_ini_pathfile=undefined
	qpkg_repo_path=undefined

	readonly TARGET_SERVICE_PATHFILE=/etc/init.d/antivirus.sh
	readonly BACKUP_SERVICE_PATHFILE=$TARGET_SERVICE_PATHFILE.bak

	readonly GET_DAEMON_PORT_CMD=''
	readonly GET_UI_PORT_CMD=''
	readonly GET_UI_PORT_SECURE_CMD=''
	readonly GET_UI_PORT_SECURE_ENABLED_TEST_CMD=''
	readonly GET_UI_LISTENING_ADDRESS_CMD=''

	}

LoadLib()
	{

	local library_path="$(/usr/bin/readlink "$0")"
	[[ -z $library_path ]] && library_path="$0"
	readonly SERVICE_LIBRARY_PATHFILE="$(/usr/bin/dirname "$library_path")"/service.lib

	if [[ -e $SERVICE_LIBRARY_PATHFILE ]]; then
		. $SERVICE_LIBRARY_PATHFILE
	else
		printf '\033[1;31m%s\033[0m: %s\n' 'derp' "QPKG service function library not found, can't continue."
		exit 1
	fi

	}

StartQPKG()
	{

	IsError && return
	MakePaths
	WaitForGit || { SetError; return 1 ;}

	if [[ ! -e $BACKUP_SERVICE_PATHFILE ]]; then
		cp "$TARGET_SERVICE_PATHFILE" "$BACKUP_SERVICE_PATHFILE"

		# mod base references
		/bin/sed -i 's|/usr/local/bin/clamscan|/opt/sbin/clamscan|' "$TARGET_SERVICE_PATHFILE"
		/bin/sed -i 's|/usr/local/bin/freshclam|/opt/sbin/freshclam|' "$TARGET_SERVICE_PATHFILE"

		# disable dryrun. The new ClamAV engine (0.102.4) doesn't support the '--dryrun' or '--countfile=' options.
		# match second occurrence only. First one is used by Mcafee. Solution here: https://unix.stackexchange.com/a/403272
		/bin/sed -i ':a;N;$!ba; s|/bin/sh -c "$AV_SCAN_PATH $DRY_RUN_OPTIONS --dryrun|#/bin/sh -c "$AV_SCAN_PATH $DRY_RUN_OPTIONS --dryrun|2' "$TARGET_SERVICE_PATHFILE"

		# mod 'clamscan' runtime options
		# match second occurrence only. First one is used by Mcafee.
		/bin/sed -i ':a;N;$!ba; s|OPTIONS="$OPTIONS --countfile=/tmp/antivirous.job.$job_id.scanning"|OPTIONS="$OPTIONS --database=$ANTIVIRUS_CLAMAV"|2' "$TARGET_SERVICE_PATHFILE"

		# mod 'freshclam' runtime options
		/bin/sed -i 's|$FRESHCLAM -u admin -l /tmp/.freshclam.log|$FRESHCLAM -u admin --config-file=$FRESHCLAM_CONFIG --datadir=$ANTIVIRUS_CLAMAV -l /tmp/.freshclam.log|' "$TARGET_SERVICE_PATHFILE"

		eval "$TARGET_SERVICE_PATHFILE" restart &>/dev/null
	fi

	/bin/grep -q freshclam /etc/profile || echo "alias freshclam='/opt/sbin/freshclam -u admin --config-file=/etc/config/freshclam.conf --datadir=/share/$(/sbin/getcfg Public path -f /etc/config/smb.conf | cut -d '/' -f 3)/.antivirus/usr/share/clamav -l /tmp/.freshclam.log'" >> /etc/profile

	DisplayCommitToLog 'start: OK'

	return 0

	}

StopQPKG()
	{

	IsError && return

	if [[ -e $BACKUP_SERVICE_PATHFILE ]]; then
		mv "$BACKUP_SERVICE_PATHFILE" "$TARGET_SERVICE_PATHFILE"

		eval "$TARGET_SERVICE_PATHFILE" restart &>/dev/null
	fi

	/bin/sed -i '/freshclam/d' /etc/profile
	DisplayCommitToLog 'stop: OK'

	return 0

	}

StatusQPKG()
	{

	IsNotError || return
	IsPackageActive && exit 0 || exit 1

	}

LoadLib
ProcessArgs
