#!/usr/bin/env bash

echo -n 'updating QPKG fields ... '

dontedit="# do not edit this file - it should only be built with the 'build-manager.sh' script"
branch=$(<~/scripts/nas/sherpa/support/branch.txt)
source=$(<~/scripts/nas/sherpa/support/sherpa.manager.source)
source=$(sed "s|<?dontedit?>|$dontedit|" <<< "$source")
source=$(sed "s|<?year?>|$(date '+%Y')|" <<< "$source")
source=$(sed "s|<?today?>|$(date '+%y%m%d')|" <<< "$source")
source=$(sed "s|<?branch?>|$branch|" <<< "$source")

echo "$source" > ~/scripts/nas/sherpa/sherpa.manager.sh

echo 'done!'
